debug: false
timerInterval: 45.0
serverId: 1                   # 0 in DB - print for all servers
serverIp: ""    # it`s optional param for domen`s IP
htmlMsgDuration: 3            # in sec
database:
  host: ""
  user: ""
  pass: ""
  base: ""
  port: 5432
  schema: ""